version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped
    environment:
      - ENVIRONMENT=development
    networks:
      - pentest-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      # For browser access
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      # For internal container access
      - NEXT_INTERNAL_API_URL=http://backend:8000
    networks:
      - pentest-network
    command: npm run dev

networks:
  pentest-network:
    driver: bridge 